import * as effects from './effects/effects';

export default {
  lark: effects.lark,
  reyes: effects.reyes,
  juno: effects.juno,
  slumber: effects.slumber,
  crema: effects.crema,
  ludwig: effects.ludwig,
  aden: effects.aden,
  perpetua: effects.perpetua,
  amaro: effects.amaro,
  mayfair: effects.mayfair,
  rise: effects.rise,
  hudson: effects.hudson,
  valencia: effects.valencia,
  xpro2: effects.xpro2,
  sierra: effects.sierra,
  willow: effects.willow,
  lofi: effects.lofi,
  earlybird: effects.earlybird,
  brannan: effects.brannan,
  inkwell: effects.inkwell,
  hefe: effects.hefe,
  nashville: effects.nashville,
  sutro: effects.sutro,
  toaster: effects.toaster,
  walden: effects.walden,
  nineteenseventyseven: effects.nineteenSeventySeven,
  kelvin: effects.kelvin,
  enhance: effects.enhance,
  grayscale: effects.grayscale,
  sepia: effects.sepia,
  luminance: effects.luminance,
  opacity: effects.opacity,
  brighten: effects.brighten,
  darken: effects.darken,
  threshold: effects.threshold,
  negaposi: effects.negaposi,
  brightnesscontrast: effects.brightnessContrast,
  huerotate: effects.hueRotate,
  saturate: effects.saturate,
  horizontalflip: effects.horizontalFlip,
  verticalflip: effects.verticalFlip,
  doubleflip: effects.doubleFlip,
  horizontalmirror: effects.horizontalMirror,
  verticalmirror: effects.verticalMirror,
  xymirror: effects.XYMirror,
  none: () => {},
};
